version: '2'

networks:
  cesbooks_network:
    driver: bridge

services:

  librarydb:
    image: mariadb
    restart: always
    volumes:
      - ./migrations/mysql-migrations.sql:/docker-entrypoint-initdb.d/mysql-migrations.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_APPLICATION_USER}
      MYSQL_PASSWORD: ${DB_APPLICATION_PASSWORD}
    networks:
      - cesbooks_network
    command: --innodb-flush-method=fsync --innodb-use-native-aio=0
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      timeout: 2s
      retries: 10
    ports:
      - "3309:3306"
    expose:
      - "3309"

  libraryapp:
    image: redyelruc/ces-books:4.0
    environment:
      DATABASE: mysql://${DB_APPLICATION_USER}:${DB_APPLICATION_PASSWORD}@librarydb:3306/${DB_NAME}
    networks:
      - cesbooks_network
    ports:
      - "80:80"
    expose:
      - "80"
    depends_on:
      librarydb:
        condition: service_healthy
